spring.application.name=SpringBootSecurityPostgresqlApplication

# La URL de Aiven sí puedes dejarla (o ponerla como variable también)
spring.datasource.url=jdbc:postgresql://pg-anareyesh-reyeshernandezanamaria.i.aivencloud.com:17317/defaultdb?sslmode=require

# El resto lo dejamos como variables (Render las reemplazará)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

demopg.app.jwtSecret=${JWT_SECRET}
demopg.app.jwtExpirationMs=259200000
