spring.application.name=SpringBootSecurityPostgresqlApplication

# Render expone el puerto en la variable PORT.
server.port=${PORT:8080}

# Si defines DB_URL en Render, se usa esa URL. Si no, queda tu URL actual como respaldo.
spring.datasource.url=${DB_URL:jdbc:postgresql://pg-anareyesh-reyeshernandezanamaria.i.aivencloud.com:17317/defaultdb?sslmode=require}

# El resto lo dejamos como variables (Render las reemplazará)
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

demopg.app.jwtSecret=${JWT_SECRET}
demopg.app.jwtExpirationMs=259200000
